name: Deploy Dist Folder
on: 
    push:        
      branches:
        - main
        - 'master/**'                    #                                       this code is run the workflow if change occurs inside code only not like read file
      paths-ignore:
        - README.md 
        - '.github/workflows/*'
    workflow_dispatch: 
jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Get Code   
              uses: actions/checkout@v6
              # run: |
              #   echo "Cloning app"
              #   echo "${{toJson(github)}}"
              #   git clone https://github.com/${{github.repository}}.git myfiles
              #   cd myfiles && ls
            - name: Setup Node
              uses: ./.github/actions/setupnode
            - name: Run Tests
              run: npm run test
    build:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - name: Get Code   
              uses: actions/checkout@v6
            - name: Setup Node
              uses: ./.github/actions/setupnode
            - name: Build Project
              run: npm run build
            - name: Upload Dist Artifact
              uses: actions/upload-artifact@v4
              with: 
                  name: dist-files
                  path: dist 

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Download Dist Artifact
            uses: actions/download-artifact@v4
            with:
                name: dist-files
                path: dist
          - name: Deploy Dist
            run: | 
               echo 'deploying below files'
               ls dist
               echo 'Deployment completed'
                 